name: IPFS Kubo
on:
  push:
    branches: [main]
    paths:
      - 'ipfs-kubo/**'
      - '.github/workflows/ipfs-kubo.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./ipfs-kubo/
          push: true
          tags: ghcr.io/ab-lab113/zonefree-ipfs:latest
